trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
jobs:
- job: job1
  steps:trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Build
  jobs:
    - job: firstjob
      steps:
      - bash: echo Build First Job
    - job: SecondJob
      steps:
      - bash: echo Build Second Job
- stage: DevDeploy
  jobs:
    - job: DevFist
      steps:
      - bash: echo Dev First Job
    - job: DevSeccond
      steps:
      - bash: echo Dev Second Job
- stage: QADeploy
  jobs:
    - job: QAJob
      steps:
      - bash: echo QA First Job
- stage: ProdDeploy
  jobs:
    - job: ProductionsJob
      steps:
      - bash: echo Production First Job
  - script: echo Job1 - Hello, world! Changed
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line scripts'
- job: job2
  dependsOn: job1
  steps:
  - script: echo Job2
    displayName: 'Run a one-line script'
- job: job3
  dependsOn: job2
  steps:
  - script: echo Job3
    displayName: 'Run a one-line script'
- job: job4
  dependsOn:
  - job2
  - job3
  steps:
  - script: echo Job 4
    displayName: 'Run a one-line script'